services:
services:
  - type: web
    name: trading-econ-bot
    env: python
    plan: free
    runtime: python3.11       # <- Python 3.11 stabile per python-telegram-bot v13
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
